[package]
name = "kindle-notes-cli"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kindle-notes-core = { path = "../kindle-notes-core"}
